[tool.ruff]
select = ["ALL"]
ignore = ["E501", "D415", "T20", "PLR1722", "ERA001", "ANN101", "D203", "D213", "C901", "COM812"]
target-version = "py311"

[tool.ruff.per-file-ignores]
"*_test.py" = ["S101", "D101", "D102", "ANN201"]
"abc.py" = ["D102"]

[tool.isort]
profile = "black"
